### ISSUE TITLE
The code is non functional

### ISSUE THREAD

**Issue by harshnagarkar** [jjjacobsen/multi-threaded-DNS-lookup#1]
Hi there,
The code that you uploaded is not working when request is failing.
Could you please check and let me know

**Comment by harshnagarkar** [comment]
The output file generates successfully

**Comment by jjjacobsen** [comment]
I wrote this code a long time ago, and it worked then. The part that is probably failing now is dnslookup() in util.c. But it seems like you figured it out anyways. Good luck
